title: Blog - Anshaj
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Anshaj Khare
  tagline: "Works as a data scientist.\r\nTechnologically audacious.\nLoves writing code and working with data. "
  profile_img: >-
    https://res.cloudinary.com/practicaldev/image/fetch/s--Dsq1PAo_--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/324810/0957571a-a8f2-42fd-8d04-c1963dcd5ce3.png
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; All rights reserved.'
  
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
